services:
  traefik:
    image: "traefik:v3.6"
    networks:
      - traefik_proxy
    ports:
      # Expose Traefik's entry points to the Swarm
      # Swarm requires the long syntax for ports.
    - target: 80 # Container port (Traefik web entry point)
      published: 80 # Host port exposed on the nodes
      protocol: tcp
      # 'host' mode binds directly to the node's IP where the task runs.
      # 'ingress' mode uses Swarm's Routing Mesh (load balances across nodes).
      # Choose based on your load balancing strategy. 'host' is often simpler if using an external LB.
      mode: host

    - target: 8080 # Container port (Traefik web entry point)
      published: 8080 # Host port exposed on the nodes
      protocol: tcp
      # 'host' mode binds directly to the node's IP where the task runs.
      # 'ingress' mode uses Swarm's Routing Mesh (load balances across nodes).
      # Choose based on your load balancing strategy. 'host' is often simpler if using an external LB.
      mode: host

    - target: 443 # Container port ( Traefik websecure entry point)
      published: 443 # Host port
      protocol: tcp
      mode: host
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "/traefik/traefik.yml:/etc/traefik/traefik.yml:r0"
    deploy:
      placement:
        constraints:
          - "node.hostname == docker-swarm-manager"
      labels:
        - "traefik.enable=true"

        # Dashboard router
        - "traefik.http.routers.dashboard.rule=Host(`dashboard.darkfleetlabs.internal`)"
        - "traefik.http.routers.dashboard.entrypoints=websecure"
        - "traefik.http.routers.dashboard.service=api@internal"

        # Service hint
        - "traefik.http.services.traefik.loadbalancer.server.port=8080"


networks:
  traefik_proxy:
    driver: overlay
    attachable: true
