all:
  hosts:
    docker-swarm-manager:
      ansible_host: 192.168.1.10
      ansible_user: root
    docker-swarm-worker-1:
      ansible_host: 192.168.1.11
      ansible_user: root
    docker-swarm-worker-2:
      ansible_host: 192.168.1.12
      ansible_user: root
    docker-swarm-worker-3-gpu:
      ansible_host: 192.168.1.13
      ansible_user: root
    adguard-home:
      ansible_host: 192.168.1.9
      ansible_user: root
  children:
    docker-swarm:
      hosts:
        docker-swarm-manager:
        internal-apps:
        external-apps:
  vars:
    ansible_python_interpreter: /usr/bin/python3
    join_token: SWMTKN-1-1hwnzrcqhyl36iycfveoa1suiy8dpfwwezn1l72ishp0j3whwd-e9s8ehh89ikuou4bh0d18yzfl
