all:
  hosts:
    docker-swarm-manager:
      ansible_host: 192.168.1.10
      ansible_user: root
    internal-apps:
      ansible_host: 192.168.1.11
      ansible_user: root
    external-apps:
      ansible_host: 192.168.1.12
      ansible_user: root
    adguard-home:
      ansible_host: 192.168.1.9
      ansible_user: root
  children:
    docker-swarm:
      hosts:
        docker-swarm-manager:
        internal-apps:
        external-apps:
  vars:
    ansible_python_interpreter: /usr/bin/python3
