all:
  hosts:
    homelab:
      ansible_host: 192.168.1.10
      ansible_user: root
    adguard-home:
      ansible_host: 192.168.1.9
      ansible_user: root
  children:

  vars:
    ansible_python_interpreter: /usr/bin/python3
